FROM node:18-alpine as builder 
WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build
EXPOSE 3000
ENTRYPOINT ['npm']
CMD [' start']

FROM nginx:alphine as production
WORKDIR  /usr/share/nginx/html
RUN rm -rf *
COPY --from=builder /app/build .

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]